namespace Casino.Common.Enum;

public enum Command
{
    GetGames,
    Start,
    ToMenu,
    GetBalance,
    ChooseFootball,
    ChooseDice,
    HitBall,
    PlayDice,
    DiceBet,
    Settings,
    PlayFootball,
    DoNothing,
    ChangeFootballBet,
    ChangeDiceBet,
    SwitchLanguage,
    DepositByTon,
    DepositMethods,
    WithdrawBalance,
    Balance,
    DepositInstruction,
    ConfirmWithdraw,
    ChooseDarts,
    PlayDarts,
    ChangeDartsBet,
    ThrowDart,
    DepositByCard,
    CreateDepositInvoice,
    ChangeDepositAmount,
    BackToDepositByCardFromDeposit,
    StartAfterDepositing
}