namespace Casino.Common.Enum;

public enum Command
{
    GetGames,
    Start,
    ToMenu,
    HitBall,
    PlayDice,
    DiceBet,
    Settings,
    PlayFootball,
    DoNothing,
    ChangeFootballBet,
    ChangeDiceBet,
    SwitchLanguage,
    DepositByTon,
    DepositMethods,
    WithdrawBalance,
    Balance,
    DepositInstruction,
    ConfirmWithdraw,
    PlayDarts,
    ChangeDartsBet,
    ThrowDarts,
    DepositByCard,
    CreateDepositInvoice,
    ChangeDepositAmount,
    BackToDepositByCardFromDeposit,
    StartAfterDepositing,
    PlayBasketball,
    ChangeBasketBet,
    ThrowBasketBall,
    ChooseGame
}